# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-15 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SipperRun',
            fields=[
                ('target_folder', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('genesippr_status', models.CharField(default='Unprocessed', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SippingMetadata',
            fields=[
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sipper.SipperRun')),
                ('log_filepath', models.CharField(default='N/A', max_length=512)),
                ('recent_output_1', models.CharField(default='-', max_length=512)),
                ('recent_output_1_time', models.CharField(default='-', max_length=512)),
                ('recent_output_2', models.CharField(default='-', max_length=512)),
                ('recent_output_2_time', models.CharField(default='-', max_length=512)),
                ('recent_output_3', models.CharField(default='-', max_length=512)),
                ('recent_output_3_time', models.CharField(default='-', max_length=512)),
                ('recent_output_4', models.CharField(default='-', max_length=512)),
                ('recent_output_4_time', models.CharField(default='-', max_length=512)),
                ('recent_output_5', models.CharField(default='-', max_length=512)),
                ('recent_output_5_time', models.CharField(default='-', max_length=512)),
                ('cycles', models.CharField(default='N/A', max_length=16)),
                ('miseq_path', models.CharField(default='N/A', max_length=512)),
                ('miseq_folder', models.CharField(default='N/A', max_length=512)),
                ('fastq_destination', models.CharField(default='N/A', max_length=512)),
                ('samplesheet', models.CharField(default='N/A', max_length=512)),
            ],
        ),
    ]
